api-version: 1.16
name: SiriusGambling
main: sirius.gambling.SiriusGambling
version: 1.0
depend: [Vault]
authors: [Emuq, Rishum]
commands:
  gamble:
    description: Gamble away your hard earned money!
    usage: /<command> (bet)
